import UserTemplate from "@/components/userTemplate"
import UserList from "../../userList"
import { Toaster } from "sonner"


export const metadata = {
    title: 'Marketplace',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <div>
            <Toaster position="top-right" richColors/>
            <UserTemplate title="" id="marketplace" menuList={UserList}>
                {children}
            </UserTemplate>
        </div>
    )
}

export default RootLayout