import ManagerTemplate from "@/components/managerTemplate"
import MenuList from "../../menuList"
import { Toaster } from "sonner"

export const metadata = {
    title: 'User | Ordering System',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <div>
            <Toaster position="top-right" richColors />
            <ManagerTemplate title="" id="user" menuList={MenuList}>
                {children}
            </ManagerTemplate>
        </div>
    )
}

export default RootLayout
