import UserTemplate from "@/components/userTemplate"
import UserList from "../../userList"

export const metadata = {
    title: 'Plant Guide',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <UserTemplate title="" id="plantguide" menuList={UserList}>
            {children}
        </UserTemplate>
    )
}

export default RootLayout